export { crearDeck } from './crear-deck'
export { PedirCarta as pedirCarta } from './pedir-carta'
export { valorCarta } from './valor-carta'
export { turnoComputadora } from './turno-computadora'
export { crearCartaHtml } from './crear-carta-html'
